version: "3.8"

networks:
  docknode-sei:
    driver: bridge

volumes:
  seid_data: {}
  seid_wasm: {}
  caddy_data: {}
  caddy_config: {}

services:
  seid:
    image: "sei-chain/seid:latest"
    restart: unless-stopped
    ports:
      - "26656:26656"
      - "26657:26657"
      - "1317:1317"
    volumes:
      - seid_data:/root/.seid/data
      - seid_wasm:/root/.seid/wasm
      - ./seid:/root/.seid/config:rw
    command: >
      /usr/bin/seid start
      --mode full
      --moniker docknode-sei
      --home /root/.seid
      --chain-id pacific-1
    networks:
      - docknode-sei
    depends_on:
      - caddy

  nodeexporter:
    image: prom/node-exporter:v1.5.0
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.rootfs=/rootfs"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)"
    expose:
      - 9100
    networks:
      - docknode-sei

  caddy:
    image: caddy:2-alpine
    ports:
      - "80:80"
      - "443:443"
      - "9100:9100"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - METRICS_USERS=${METRICS_USERS:?err}
      - RPC_USERS=${RPC_USERS:?err}
      - HOST=${HOST:?err}
    networks:
      - docknode-sei
